<?php

namespace ContainerALjiNh2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManagerInterfaceService extends Kematjaya_ExportBundle_Test_AppKernelTestTestDebugContainer
{
    /**
     * Gets the public 'Kematjaya\Export\Manager\ManagerInterface' shared autowired service.
     *
     * @return \Kematjaya\Export\Manager\ExportManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/kematjaya/export/src/Manager/ManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/kematjaya/export/src/Manager/ExportManager.php';

        return $container->services['Kematjaya\\Export\\Manager\\ManagerInterface'] = new \Kematjaya\Export\Manager\ExportManager();
    }
}
