services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kematjaya\Export\Manager\ManagerInterface:
        class: Kematjaya\Export\Manager\ExportManager
        public: true