services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kematjaya\Export\Manager\ManagerInterface:
        class: Kematjaya\Export\Manager\ExportManager
        public: true
        
    Kematjaya\Export\Normalizer\FileNormalizerInterface:
        class: Kematjaya\Export\Normalizer\FileNormalizer
        
    kematjaya.file_normalizer:
        alias: Kematjaya\Export\Normalizer\FileNormalizerInterface
        public: true