<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerALjiNh2\Kematjaya_ExportBundle_Test_AppKernelTestTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerALjiNh2/Kematjaya_ExportBundle_Test_AppKernelTestTestDebugContainer.php') {
    touch(__DIR__.'/ContainerALjiNh2.legacy');

    return;
}

if (!\class_exists(Kematjaya_ExportBundle_Test_AppKernelTestTestDebugContainer::class, false)) {
    \class_alias(\ContainerALjiNh2\Kematjaya_ExportBundle_Test_AppKernelTestTestDebugContainer::class, Kematjaya_ExportBundle_Test_AppKernelTestTestDebugContainer::class, false);
}

return new \ContainerALjiNh2\Kematjaya_ExportBundle_Test_AppKernelTestTestDebugContainer([
    'container.build_hash' => 'ALjiNh2',
    'container.build_id' => '060e2224',
    'container.build_time' => 1607651801,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerALjiNh2');
